### ISSUE TITLE
error instaling wallet "Permission denied"

### ISSUE THREAD

**Issue by granatgas** [scriptexpert/Eurocoin#1]
hi, can you help me?
i got this message after running
chmod +x autogen.sh
./autogen.sh
./configure
all fine 

but if i try to "make"

showing this error

/bin/bash: ../share/genbuild.sh: Permission denied
make[3]: *** [obj/build.h] Error 126
make[3]: Leaving directory `/home/grantgas/Eurocoin/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/grantgas/Eurocoin/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/grantgas/Eurocoin/src'
make: *** [all-recursive] Error 1

**Comment by scriptexpert** [comment]
Hi,

Try this

./autogen.sh
./configure --without-gui
make

Regards,

Martin




---- On Tue, 27 Oct 2015 23:54:28 -0400 granatgas&lt;notifications@github.com&gt; wrote ---- 

hi, can you help me?
 i got this message after running
 chmod +x autogen.sh
 ./autogen.sh
 ./configure
 all fine 
 but if i try to "make"
 showing this error
 /bin/bash: ../share/genbuild.sh: Permission denied 
 make[3]: *** [obj/build.h] Error 126 
 make[3]: Leaving directory /home/grantgas/Eurocoin/src' 
 make[2]: *** [all-recursive] Error 1 
 make[2]: Leaving directory/home/grantgas/Eurocoin/src' 
 make[1]: *** [all] Error 2 
 make[1]: Leaving directory `/home/grantgas/Eurocoin/src' 
 make: *** [all-recursive] Error 1

**Comment by granatgas** [comment]
hi, 
still same error

Making all in src
make[1]: Entering directory `/home/grantgas/Eurocoin/src'
make  all-recursive
make[2]: Entering directory `/home/grantgas/Eurocoin/src'
Making all in .
make[3]: Entering directory `/home/grantgas/Eurocoin/src'
  CXX      addrman.o
  CXX      alert.o
  CXX      bloom.o
  CXX      checkpoints.o
  CXX      coins.o
  CXX      init.o
  CXX      keystore.o
  CXX      leveldbwrapper.o
  CXX      main.o
  CXX      miner.o
  CXX      net.o
  CXX      noui.o
  CXX      rpcblockchain.o
  CXX      rpcmining.o
  CXX      rpcmisc.o
  CXX      rpcnet.o
  CXX      rpcrawtransaction.o
  CXX      rpcserver.o
  CXX      txdb.o
  CXX      txmempool.o
  AR       libbitcoin_server.a
  CXX      base58.o
  CXX      allocators.o
  CXX      chainparams.o
  CXX      core.o
  CXX      hash.o
  CXX      key.o
  CXX      netbase.o
  CXX      protocol.o
  CXX      rpcprotocol.o
  CXX      script.o
  CXX      sync.o
  CXX      util.o
/bin/bash: ../share/genbuild.sh: Permission denied
make[3]: *** [obj/build.h] Error 126
make[3]: Leaving directory `/home/grantgas/Eurocoin/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/grantgas/Eurocoin/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/grantgas/Eurocoin/src'
make: *** [all-recursive] Error 1

**Comment by scriptexpert** [comment]
Chmod 777 genbuild.sh


Regards,

Martin




---- On Wed, 28 Oct 2015 00:22:33 -0400 granatgas&lt;notifications@github.com&gt; wrote ---- 

hi, 
 still same error
 Making all in src
 make[1]: Entering directory /home/grantgas/Eurocoin/src'
 make all-recursive
 make[2]: Entering directory/home/grantgas/Eurocoin/src'
 Making all in .
 make[3]: Entering directory /home/grantgas/Eurocoin/src'
 CXX addrman.o
 CXX alert.o
 CXX bloom.o
 CXX checkpoints.o
 CXX coins.o
 CXX init.o
 CXX keystore.o
 CXX leveldbwrapper.o
 CXX main.o
 CXX miner.o
 CXX net.o
 CXX noui.o
 CXX rpcblockchain.o
 CXX rpcmining.o
 CXX rpcmisc.o
 CXX rpcnet.o
 CXX rpcrawtransaction.o
 CXX rpcserver.o
 CXX txdb.o
 CXX txmempool.o
 AR libbitcoin_server.a
 CXX base58.o
 CXX allocators.o
 CXX chainparams.o
 CXX core.o
 CXX hash.o
 CXX key.o
 CXX netbase.o
 CXX protocol.o
 CXX rpcprotocol.o
 CXX script.o
 CXX sync.o
 CXX util.o
 /bin/bash: ../share/genbuild.sh: Permission denied
 make[3]: *** [obj/build.h] Error 126
 make[3]: Leaving directory/home/grantgas/Eurocoin/src'
 make[2]: *** [all-recursive] Error 1
 make[2]: Leaving directory /home/grantgas/Eurocoin/src'
 make[1]: *** [all] Error 2
 make[1]: Leaving directory/home/grantgas/Eurocoin/src'
 make: *** [all-recursive] Error 1

**Comment by granatgas** [comment]
SOLVED
thank you :)
